# @Author: arpitkhandelwal
# @Date:   11-Feb-2017
# @Last modified by:   arpitkhandelwal
# @Last modified time: 11-Feb-2017

language: java
jdk:
  - oraclejdk8
sudo: true

script:
  - mvn test

notifications:
  slack: p632:20oR0X45QVtC9RACNHghchWR
    on_success: never
    on_failure: always

# addons:
#   code_climate:
#     repo_token:
#
# after_script:
#    codeclimate-test-reporter < lcov.info
